// ============================================================
// FBW Level Editor — standalone Qt5 app
// Build & run:  ./run
// ============================================================
#include <QApplication>
#include <QMainWindow>
#include <QWidget>
#include <QPainter>
#include <QMouseEvent>
#include <QKeyEvent>
#include <QPushButton>
#include <QLabel>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QComboBox>
#include <QSpinBox>
#include <QGroupBox>
#include <QTextEdit>
#include <QSplitter>
#include <QStatusBar>
#include <QAction>
#include <QScrollArea>
#include <QLineEdit>
#include <QString>
#include <QRegularExpression>
#include <vector>

#define TILE_EMPTY  0
#define TILE_SOLID  1
#define TILE_LAVA   2
#define TILE_WATER  3
#define TILE_POISON 4

#define TILE_CONVEYOR_R 10
#define TILE_CONVEYOR_L 11
#define TILE_GEM_FB     20
#define TILE_GEM_WG     21
#define TILE_DOOR_FB    30
#define TILE_DOOR_WG    31
#define TILE_BTN_0      40
#define TILE_BTN_1      41
#define TILE_GATE_0     50
#define TILE_GATE_1     51
#define TILE_TELEPORT_0 60
#define TILE_TELEPORT_1 61
#define TILE_SPAWN_FB   60
#define TILE_SPAWN_WG   61

#define MAP_ROWS    16
#define MAP_COLS    20
#define TILE_PX     38

static QColor tileColor(int t) {
    switch (t) {
        case TILE_SOLID:  return QColor(90, 75, 50);
        case TILE_LAVA:   return QColor(230, 70, 10);
        case TILE_WATER:  return QColor(30, 110, 220);
        case TILE_POISON: return QColor(60, 200, 60);
        case TILE_CONVEYOR_R: return QColor(100, 100, 120);
        case TILE_CONVEYOR_L: return QColor(80, 80, 100);
        case TILE_GEM_FB: return QColor(255, 50, 50);
        case TILE_GEM_WG: return QColor(50, 50, 255);
        case TILE_DOOR_FB: return QColor(200, 100, 50);
        case TILE_DOOR_WG: return QColor(50, 100, 200);
        case TILE_BTN_0: return QColor(40, 140, 220);
        case TILE_BTN_1: return QColor(220, 120, 20);
        case TILE_GATE_0: return QColor(40, 140, 220, 150);
        case TILE_GATE_1: return QColor(220, 120, 20, 150);
        case TILE_TELEPORT_0: return QColor(150, 0, 255);
        case TILE_TELEPORT_1: return QColor(150, 0, 255);
        default:          return QColor(25, 25, 35);
    }
}

static const char* tileName(int t) {
    switch (t) {
        case TILE_SOLID: return "SOLID";
        case TILE_LAVA: return "LAVA";
        case TILE_WATER: return "WATER";
        case TILE_POISON: return "POISON";
        case TILE_CONVEYOR_R: return "CONVEYOR RIGHT";
        case TILE_CONVEYOR_L: return "CONVEYOR LEFT";
        case TILE_GEM_FB: return "GEM FIREBOY";
        case TILE_GEM_WG: return "GEM WATERGIRL";
        case TILE_DOOR_FB: return "DOOR FIREBOY";
        case TILE_DOOR_WG: return "DOOR WATERGIRL";
        case TILE_BTN_0: return "BUTTON BLUE";
        case TILE_BTN_1: return "BUTTON ORANGE";
        case TILE_GATE_0: return "GATE BLUE";
        case TILE_GATE_1: return "GATE ORANGE";
        case TILE_TELEPORT_0: return "TELEPORT A";
        case TILE_TELEPORT_1: return "TELEPORT B";
        default: return "EMPTY";
    }
}

class GridCanvas : public QWidget {
    Q_OBJECT
public:
    int grid[MAP_ROWS][MAP_COLS];
    int activeTile = TILE_SOLID;
    bool showCoords = true;

    int fbRow = 14, fbCol = 3;
    int wgRow = 14, wgCol = 16;
    int gateHeight = 2;

    std::vector<std::vector<std::vector<int>>> undoStack;

    explicit GridCanvas(QWidget* parent = nullptr) : QWidget(parent) {
        setFixedSize(MAP_COLS * TILE_PX + 1, MAP_ROWS * TILE_PX + 1);
        setMouseTracking(true);
        fill(TILE_EMPTY);
    }

    void pushUndo() {
        std::vector<std::vector<int>> state(MAP_ROWS, std::vector<int>(MAP_COLS));
        for (int r = 0; r < MAP_ROWS; r++)
            for (int c = 0; c < MAP_COLS; c++)
                state[r][c] = grid[r][c];
        undoStack.push_back(state);
        if (undoStack.size() > 50) undoStack.erase(undoStack.begin());
    }

    void popUndo() {
        if (undoStack.empty()) return;
        auto state = undoStack.back();
        undoStack.pop_back();
        for (int r = 0; r < MAP_ROWS; r++)
            for (int c = 0; c < MAP_COLS; c++)
                grid[r][c] = state[r][c];
        update();
    }

    void fill(int tile) {
        pushUndo();
        for (int r = 0; r < MAP_ROWS; r++)
            for (int c = 0; c < MAP_COLS; c++) {
                if (r == 0 || r == MAP_ROWS-1 || c == 0 || c == MAP_COLS-1)
                    grid[r][c] = TILE_SOLID;
                else
                    grid[r][c] = tile;
            }
        update();
    }

    QString generateCode(const QString& levelName, int levelNum, int bgStyle, int gateHeight) const {
        QString out;
        out += QString("// ============================================================\n");
        out += QString("// LEVEL %1 - \"%2\"\n").arg(levelNum).arg(levelName);
        out += QString("// Generated by FBW Level Editor\n");
        out += QString("// ============================================================\n");
        out += QString("LevelData makeLevel%1() {\n").arg(levelNum);
        out += QString("    LevelData lv;\n");
        out += QString("    lv.num = %1; lv.bgStyle = %2;\n").arg(levelNum).arg(bgStyle);
        out += QString("    strcpy(lv.name, \"%1\");\n\n").arg(levelName);

        out += "    int map[MAP_ROWS][MAP_COLS] = {\n";
        for (int r = 0; r < MAP_ROWS; r++) {
            out += "        {";
            for (int c = 0; c < MAP_COLS; c++) {
                int t = grid[r][c];
                if (t == TILE_SOLID)       out += "S";
                else if (t == TILE_LAVA)   out += "L";
                else if (t == TILE_WATER)  out += "W";
                else if (t == TILE_POISON) out += "P";
                else if (t == TILE_CONVEYOR_R) out += "R";
                else if (t == TILE_CONVEYOR_L) out += "Q";
                else out += "E";
                if (c < MAP_COLS-1) out += ",";
            }
            out += "}";
            if (r < MAP_ROWS-1) out += ",";
            out += QString("  // %1\n").arg(r);
        }
        out += "    };\n";
        out += "    bstInit(&lv.tileTree);\n";
        out += "    for(int r=0;r<MAP_ROWS;r++) for(int c=0;c<MAP_COLS;c++) bstInsert(&lv.tileTree,r,c,map[r][c]);\n\n";

        out += QString("    lv.fireboyStartX   = %1*TILE_SIZE; lv.fireboyStartY   = %2*TILE_SIZE - PLAYER_H;\n").arg(fbCol).arg(fbRow);
        out += QString("    lv.watergirlStartX = %1*TILE_SIZE; lv.watergirlStartY = %2*TILE_SIZE - PLAYER_H;\n\n").arg(wgCol).arg(wgRow);

        int gemCount=0, convCount=0, btnCount=0, gateCount=0, hazardCount=0, teleportCount=0;
        QString gems, convs, btns, gates, hazards, teleports;
        
        // Find doors
        int dFbX=1, dFbY=1, dWgX=3, dWgY=1;
        for (int r=0; r<MAP_ROWS; r++) {
            for (int c=0; c<MAP_COLS; c++) {
                int t = grid[r][c];
                if (t == TILE_GEM_FB) gems += QString("    lv.gems[%1] = {%2*TILE_SIZE+8, %3*TILE_SIZE+8, FIREBOY, false, 0.0f};\n").arg(gemCount++).arg(c).arg(r);
                if (t == TILE_GEM_WG) gems += QString("    lv.gems[%1] = {%2*TILE_SIZE+8, %3*TILE_SIZE+8, WATERGIRL, false, 0.0f};\n").arg(gemCount++).arg(c).arg(r);
                if (t == TILE_BTN_0) btns += QString("    lv.buttons[%1] = {%2*TILE_SIZE-6, (%3+1)*TILE_SIZE-20, TILE_SIZE+24, 20, 0, false};\n").arg(btnCount++).arg(c).arg(r);
                if (t == TILE_BTN_1) btns += QString("    lv.buttons[%1] = {%2*TILE_SIZE-6, (%3+1)*TILE_SIZE-20, TILE_SIZE+24, 20, 1, false};\n").arg(btnCount++).arg(c).arg(r);
                if (t == TILE_GATE_0) gates += QString("    lv.gates[%1] = {0, %2*TILE_SIZE, %3*TILE_SIZE, TILE_SIZE, TILE_SIZE*%4, false, 0.0f};\n").arg(gateCount++).arg(c).arg(r).arg(gateHeight);
                if (t == TILE_GATE_1) gates += QString("    lv.gates[%1] = {1, %2*TILE_SIZE, %3*TILE_SIZE, TILE_SIZE, TILE_SIZE*%4, false, 0.0f};\n").arg(gateCount++).arg(c).arg(r).arg(gateHeight);
                if (t == TILE_TELEPORT_0) teleports += QString("    lv.pads[%1] = {%2*TILE_SIZE, %3*TILE_SIZE, 0, 1, 0.0f};\n").arg(teleportCount++).arg(c).arg(r);
                if (t == TILE_TELEPORT_1) teleports += QString("    lv.pads[%1] = {%2*TILE_SIZE, %3*TILE_SIZE, 1, 0, 0.0f};\n").arg(teleportCount++).arg(c).arg(r);
                if (t == TILE_DOOR_FB) { dFbX = c; dFbY = r; }
                if (t == TILE_DOOR_WG) { dWgX = c; dWgY = r; }
                
                // Hazards
                if (t == TILE_LAVA) hazards += QString("    lv.hazards[%1] = {%2*TILE_SIZE, %3*TILE_SIZE, TILE_SIZE, TILE_SIZE, TILE_LAVA};\n").arg(hazardCount++).arg(c).arg(r);
                if (t == TILE_WATER) hazards += QString("    lv.hazards[%1] = {%2*TILE_SIZE, %3*TILE_SIZE, TILE_SIZE, TILE_SIZE, TILE_WATER};\n").arg(hazardCount++).arg(c).arg(r);
                if (t == TILE_POISON) hazards += QString("    lv.hazards[%1] = {%2*TILE_SIZE, %3*TILE_SIZE, TILE_SIZE, TILE_SIZE, TILE_POISON};\n").arg(hazardCount++).arg(c).arg(r);
            }
        }

        out += QString("    lv.doors[0] = {%1*TILE_SIZE, (%2+1)*TILE_SIZE - TILE_SIZE*2.0f, TILE_SIZE*2.0f, FIREBOY, false};\n").arg(dFbX).arg(dFbY);
        out += QString("    lv.doors[1] = {%1*TILE_SIZE, (%2+1)*TILE_SIZE - TILE_SIZE*2.0f, TILE_SIZE*2.0f, WATERGIRL, false};\n\n").arg(dWgX).arg(dWgY);
        
        out += QString("    lv.gemCount = %1;\n").arg(gemCount) + gems + "\n";
        out += "    lv.conveyorCount = 0;\n";
        out += QString("    lv.buttonCount = %1;\n").arg(btnCount) + btns + "\n";
        out += QString("    lv.gateCount = %1;\n").arg(gateCount) + gates + "\n";
        out += QString("    lv.teleportCount = %1;\n").arg(teleportCount) + teleports + "\n";
        out += QString("    lv.hazardCount = %1;\n").arg(hazardCount) + hazards + "\n";
        out += "    lv.platformCount = 0;\n";
        out += "    return lv;\n}\n";
        return out;
    }

signals:
    void hovered(int r, int c, int tile);
    void spawnMoved();

protected:
    void paintEvent(QPaintEvent*) override {
        QPainter p(this);
        for (int r = 0; r < MAP_ROWS; r++) {
            for (int c = 0; c < MAP_COLS; c++) {
                QRect cell(c*TILE_PX, r*TILE_PX, TILE_PX, TILE_PX);
                p.fillRect(cell, tileColor(grid[r][c]));
                
                int t = grid[r][c];
                p.setPen(Qt::white);
                if (t == TILE_CONVEYOR_R) p.drawText(cell, Qt::AlignCenter, "C>");
                if (t == TILE_CONVEYOR_L) p.drawText(cell, Qt::AlignCenter, "<C");
                if (t == TILE_GEM_FB) p.drawText(cell, Qt::AlignCenter, "GF");
                if (t == TILE_GEM_WG) p.drawText(cell, Qt::AlignCenter, "GW");
                
                if (t == TILE_DOOR_FB || t == TILE_DOOR_WG) {
                    QRect doorRect(c*TILE_PX, (r - 2 + 1)*TILE_PX, TILE_PX, 2*TILE_PX);
                    p.fillRect(doorRect, (t == TILE_DOOR_FB) ? QColor(255,80,20, 150) : QColor(30,130,255, 150));
                    p.drawText(cell, Qt::AlignCenter, (t == TILE_DOOR_FB) ? "DF" : "DW");
                }
                if (t == TILE_GATE_0 || t == TILE_GATE_1) {
                    int h = gateHeight;
                    QRect gateRect(c*TILE_PX, r*TILE_PX, TILE_PX, h*TILE_PX);
                    p.fillRect(gateRect, (t == TILE_GATE_0) ? QColor(40,140,220, 150) : QColor(220,120,20, 150));
                    p.drawText(cell, Qt::AlignCenter, (t == TILE_GATE_0) ? "G0" : "G1");
                }
                
                if (t == TILE_BTN_0) p.drawText(cell, Qt::AlignCenter, "B0");
                if (t == TILE_BTN_1) p.drawText(cell, Qt::AlignCenter, "B1");
                if (t == TILE_TELEPORT_0) p.drawText(cell, Qt::AlignCenter, "TP0");
                if (t == TILE_TELEPORT_1) p.drawText(cell, Qt::AlignCenter, "TP1");

                if (r == fbRow && c == fbCol) {
                    p.fillRect(cell.adjusted(4,4,-4,-4), QColor(255,80,20,200));
                    p.drawText(cell, Qt::AlignCenter, "FB");
                }
                if (r == wgRow && c == wgCol) {
                    p.fillRect(cell.adjusted(4,4,-4,-4), QColor(30,130,255,200));
                    p.drawText(cell, Qt::AlignCenter, "WG");
                }
                p.setPen(QPen(QColor(50,50,70), 1));
                p.drawRect(cell);
            }
        }
    }

    void mousePressEvent(QMouseEvent* e) override { 
        pushUndo();
        paintAt(e); 
    }
    void mouseMoveEvent(QMouseEvent* e) override {
        int r = e->y()/TILE_PX, c = e->x()/TILE_PX;
        if (r>=0&&r<MAP_ROWS&&c>=0&&c<MAP_COLS) emit hovered(r,c,grid[r][c]);
        if (e->buttons()) paintAt(e);
    }
    void paintAt(QMouseEvent* e) {
        int r = e->y()/TILE_PX, c = e->x()/TILE_PX;
        if (r<0||r>=MAP_ROWS||c<0||c>=MAP_COLS) return;
        if (e->buttons() & Qt::LeftButton)  { 
            if (activeTile == TILE_SPAWN_FB) { fbRow = r; fbCol = c; emit spawnMoved(); }
            else if (activeTile == TILE_SPAWN_WG) { wgRow = r; wgCol = c; emit spawnMoved(); }
            else grid[r][c] = activeTile; 
            update(); 
        }
        if (e->buttons() & Qt::RightButton) { grid[r][c] = TILE_EMPTY;  update(); }
    }
};

class EditorWindow : public QMainWindow {
    Q_OBJECT
    GridCanvas* canvas;
    QLabel*     statusLbl;
    QComboBox*  tileCombo;
    QTextEdit*  codeView;
    QSpinBox*   fbRowSpin, *fbColSpin, *wgRowSpin, *wgColSpin, *doorHeightSpin;

public:
    EditorWindow() {
        setWindowTitle("FBW Level Editor");
        resize(1200, 750);
        QSplitter* splitter = new QSplitter(Qt::Horizontal, this);
        setCentralWidget(splitter);

        QScrollArea* scroll = new QScrollArea;
        canvas = new GridCanvas;
        scroll->setWidget(canvas);
        splitter->addWidget(scroll);

        QWidget* right = new QWidget;
        QVBoxLayout* rv = new QVBoxLayout(right);
        splitter->addWidget(right);

        // Tile Palette
        QGroupBox* palette = new QGroupBox("Tile Palette (L-Click Paint, R-Click Erase)");
        QHBoxLayout* ph = new QHBoxLayout(palette);
        tileCombo = new QComboBox;
        tileCombo->addItem("Empty", TILE_EMPTY);
        tileCombo->addItem("Solid", TILE_SOLID);
        tileCombo->addItem("Lava", TILE_LAVA);
        tileCombo->addItem("Water", TILE_WATER);
        tileCombo->addItem("Poison", TILE_POISON);
        tileCombo->addItem("Conveyor Right", TILE_CONVEYOR_R);
        tileCombo->addItem("Conveyor Left", TILE_CONVEYOR_L);
        tileCombo->addItem("Gem Fireboy", TILE_GEM_FB);
        tileCombo->addItem("Gem Watergirl", TILE_GEM_WG);
        tileCombo->addItem("Door Fireboy", TILE_DOOR_FB);
        tileCombo->addItem("Door Watergirl", TILE_DOOR_WG);
        tileCombo->addItem("Button Blue (0)", TILE_BTN_0);
        tileCombo->addItem("Button Orange (1)", TILE_BTN_1);
        tileCombo->addItem("Gate Blue (0)", TILE_GATE_0);
        tileCombo->addItem("Gate Orange (1)", TILE_GATE_1);
        tileCombo->addItem("Teleport Pad A (0)", TILE_TELEPORT_0);
        tileCombo->addItem("Teleport Pad B (1)", TILE_TELEPORT_1);
        tileCombo->insertSeparator(tileCombo->count());
        tileCombo->addItem("Set Fireboy Spawn", TILE_SPAWN_FB);
        tileCombo->addItem("Set Watergirl Spawn", TILE_SPAWN_WG);
        tileCombo->setCurrentIndex(1);
        connect(tileCombo, QOverload<int>::of(&QComboBox::currentIndexChanged), [=](int i){
            canvas->activeTile = tileCombo->itemData(i).toInt();
        });
        ph->addWidget(tileCombo);
        rv->addWidget(palette);

        // Buttons
        QHBoxLayout* tools = new QHBoxLayout;
        QPushButton* undoBtn = new QPushButton("Undo");
        connect(undoBtn, &QPushButton::clicked, canvas, &GridCanvas::popUndo);
        tools->addWidget(undoBtn);
        QPushButton* clrBtn = new QPushButton("Clear");
        connect(clrBtn, &QPushButton::clicked, [=](){ canvas->fill(TILE_EMPTY); });
        tools->addWidget(clrBtn);
        rv->addLayout(tools);

        // Spawn Spinboxes
        QGroupBox* spawns = new QGroupBox("Spawn Pos");
        QGridLayout* sg = new QGridLayout(spawns);
        sg->addWidget(new QLabel("FB Row:"), 0, 0);
        fbRowSpin = new QSpinBox; fbRowSpin->setRange(0,MAP_ROWS-1); fbRowSpin->setValue(14);
        sg->addWidget(fbRowSpin, 0, 1);
        sg->addWidget(new QLabel("Col:"), 0, 2);
        fbColSpin = new QSpinBox; fbColSpin->setRange(0,MAP_COLS-1); fbColSpin->setValue(3);
        sg->addWidget(fbColSpin, 0, 3);
        sg->addWidget(new QLabel("WG Row:"), 1, 0);
        wgRowSpin = new QSpinBox; wgRowSpin->setRange(0,MAP_ROWS-1); wgRowSpin->setValue(14);
        sg->addWidget(wgRowSpin, 1, 1);
        sg->addWidget(new QLabel("Col:"), 1, 2);
        wgColSpin = new QSpinBox; wgColSpin->setRange(0,MAP_COLS-1); wgColSpin->setValue(16);
        sg->addWidget(wgColSpin, 1, 3);
        
        sg->addWidget(new QLabel("Gate Height:"), 2, 0);
        doorHeightSpin = new QSpinBox; doorHeightSpin->setRange(1, 10); doorHeightSpin->setValue(2);
        sg->addWidget(doorHeightSpin, 2, 1);
        
        auto syncSpawns = [=]() { 
            canvas->fbRow = fbRowSpin->value(); 
            canvas->fbCol = fbColSpin->value(); 
            canvas->wgRow = wgRowSpin->value(); 
            canvas->wgCol = wgColSpin->value(); 
            canvas->gateHeight = doorHeightSpin->value();
            canvas->update(); 
        };
        connect(fbRowSpin, QOverload<int>::of(&QSpinBox::valueChanged), syncSpawns);
        connect(fbColSpin, QOverload<int>::of(&QSpinBox::valueChanged), syncSpawns);
        connect(wgRowSpin, QOverload<int>::of(&QSpinBox::valueChanged), syncSpawns);
        connect(wgColSpin, QOverload<int>::of(&QSpinBox::valueChanged), syncSpawns);
        connect(doorHeightSpin, QOverload<int>::of(&QSpinBox::valueChanged), syncSpawns);
        connect(canvas, &GridCanvas::spawnMoved, [=]() {
            fbRowSpin->blockSignals(true); fbRowSpin->setValue(canvas->fbRow); fbRowSpin->blockSignals(false);
            fbColSpin->blockSignals(true); fbColSpin->setValue(canvas->fbCol); fbColSpin->blockSignals(false);
            wgRowSpin->blockSignals(true); wgRowSpin->setValue(canvas->wgRow); wgRowSpin->blockSignals(false);
            wgColSpin->blockSignals(true); wgColSpin->setValue(canvas->wgCol); wgColSpin->blockSignals(false);
        });
        rv->addWidget(spawns);

        // Code Area
        codeView = new QTextEdit;
        codeView->setFont(QFont("Monospace", 8));
        rv->addWidget(codeView);
        
        QHBoxLayout* ch = new QHBoxLayout;
        QPushButton* loadBtn = new QPushButton("Load Code");
        QPushButton* genBtn = new QPushButton("Generate Code");
        connect(loadBtn, &QPushButton::clicked, this, &EditorWindow::loadCode);
        connect(genBtn, &QPushButton::clicked, this, &EditorWindow::generateCode);
        ch->addWidget(loadBtn);
        ch->addWidget(genBtn);
        rv->addLayout(ch);

        statusLbl = new QLabel("Ready");
        statusBar()->addWidget(statusLbl);
        connect(canvas, &GridCanvas::hovered, [=](int r, int c, int t){
            statusLbl->setText(QString("Row %1, Col %2 - %3").arg(r).arg(c).arg(tileName(t)));
        });

        QAction* undoAct = new QAction(this);
        undoAct->setShortcut(QKeySequence("Ctrl+Z"));
        connect(undoAct, &QAction::triggered, canvas, &GridCanvas::popUndo);
        addAction(undoAct);
    }

    int parseCoord(QString expr) {
        QRegularExpression re("\\(?(\\d+)(?:\\+1)?\\)?\\*TILE_SIZE");
        QRegularExpressionMatch m = re.match(expr);
        if (m.hasMatch()) return m.captured(1).toInt();
        return 0;
    }

private slots:
    void generateCode() {
        codeView->setPlainText(canvas->generateCode("Custom Level", 4, 0, doorHeightSpin->value()));
    }

    void loadCode() {
        QString text = codeView->toPlainText();
        canvas->pushUndo();
        
        // Parse map layout
        QRegularExpression reMap("\\{([SELWPQR,]+)\\}");
        QRegularExpressionMatchIterator i = reMap.globalMatch(text);
        int r = 0;
        while (i.hasNext() && r < MAP_ROWS) {
            QRegularExpressionMatch match = i.next();
            QString rowStr = match.captured(1);
            rowStr.remove(',');
            for (int c = 0; c < qMin((int)rowStr.length(), MAP_COLS); c++) {
                QChar ch = rowStr[c];
                if      (ch == 'S') canvas->grid[r][c] = TILE_SOLID;
                else if (ch == 'L') canvas->grid[r][c] = TILE_LAVA;
                else if (ch == 'W') canvas->grid[r][c] = TILE_WATER;
                else if (ch == 'P') canvas->grid[r][c] = TILE_POISON;
                else if (ch == 'R') canvas->grid[r][c] = TILE_CONVEYOR_R;
                else if (ch == 'Q') canvas->grid[r][c] = TILE_CONVEYOR_L;
                else                canvas->grid[r][c] = TILE_EMPTY;
            }
            r++;
        }

        // Parse Spawns
        QRegularExpression fbX("fireboyStartX\\s*=\\s*([^;]+);");
        QRegularExpression fbY("fireboyStartY\\s*=\\s*([^;]+);");
        if (fbX.match(text).hasMatch()) fbColSpin->setValue(parseCoord(fbX.match(text).captured(1)));
        if (fbY.match(text).hasMatch()) fbRowSpin->setValue(parseCoord(fbY.match(text).captured(1)));
        
        QRegularExpression wgX("watergirlStartX\\s*=\\s*([^;]+);");
        QRegularExpression wgY("watergirlStartY\\s*=\\s*([^;]+);");
        if (wgX.match(text).hasMatch()) wgColSpin->setValue(parseCoord(wgX.match(text).captured(1)));
        if (wgY.match(text).hasMatch()) wgRowSpin->setValue(parseCoord(wgY.match(text).captured(1)));

        // Parse entities
        auto parseList = [&](QString pattern, auto func) {
            QRegularExpression re(pattern);
            QRegularExpressionMatchIterator it = re.globalMatch(text);
            while (it.hasNext()) func(it.next());
        };

        parseList("gems\\[\\d+\\]\\s*=\\s*\\{([^,]+),\\s*([^,]+),\\s*(FIREBOY|WATERGIRL)", [&](auto m) {
            int cx = parseCoord(m.captured(1)), cy = parseCoord(m.captured(2));
            if (cy>=0 && cy<MAP_ROWS && cx>=0 && cx<MAP_COLS) 
                canvas->grid[cy][cx] = (m.captured(3) == "FIREBOY") ? TILE_GEM_FB : TILE_GEM_WG;
        });
        parseList("conveyors\\[\\d+\\]\\s*=\\s*\\{([^,]+),\\s*([^,]+),\\s*[^,]+,\\s*[^,]+,\\s*(-?\\d+)", [&](auto m) {
            int cx = parseCoord(m.captured(1)), cy = parseCoord(m.captured(2));
            if (cy>=0 && cy<MAP_ROWS && cx>=0 && cx<MAP_COLS) 
                canvas->grid[cy][cx] = (m.captured(3).toInt() > 0) ? TILE_CONVEYOR_R : TILE_CONVEYOR_L;
        });
        parseList("buttons\\[\\d+\\]\\s*=\\s*\\{([^,]+),\\s*([^,]+),\\s*[^,]+,\\s*[^,]+,\\s*(\\d+)", [&](auto m) {
            int cx = parseCoord(m.captured(1)), cy = parseCoord(m.captured(2));
            if (cy>=0 && cy<MAP_ROWS && cx>=0 && cx<MAP_COLS) 
                canvas->grid[cy][cx] = (m.captured(3) == "0") ? TILE_BTN_0 : TILE_BTN_1;
        });
        parseList("gates\\[\\d+\\]\\s*=\\s*\\{([^,]+),\\s*([^,]+),\\s*([^,]+)", [&](auto m) {
            int cx = parseCoord(m.captured(2)), cy = parseCoord(m.captured(3));
            if (cy>=0 && cy<MAP_ROWS && cx>=0 && cx<MAP_COLS) 
                canvas->grid[cy][cx] = (m.captured(1) == "0") ? TILE_GATE_0 : TILE_GATE_1;
        });
        parseList("doors\\[0\\]\\s*=\\s*\\{([^,]+),\\s*([^,]+),\\s*(?:TILE_SIZE\\*)?([^,]+)", [&](auto m) {
            int cx = parseCoord(m.captured(1)), cy = parseCoord(m.captured(2));
            if (cy>=0 && cy<MAP_ROWS && cx>=0 && cx<MAP_COLS) canvas->grid[cy][cx] = TILE_DOOR_FB;
            
            // Extract height multiplier. If format is TILE_SIZE*2.0f, m.captured(3) is "2.0f"
            QString hStr = m.captured(3);
            hStr.remove("f");
            doorHeightSpin->setValue(qRound(hStr.toFloat()));
        });
        parseList("doors\\[1\\]\\s*=\\s*\\{([^,]+),\\s*([^,]+)", [&](auto m) {
            int cx = parseCoord(m.captured(1)), cy = parseCoord(m.captured(2));
            if (cy>=0 && cy<MAP_ROWS && cx>=0 && cx<MAP_COLS) canvas->grid[cy][cx] = TILE_DOOR_WG;
        });

        canvas->update();
        statusLbl->setText("Code loaded!");
    }
};

#include "build/moc/leveleditor_moc.cpp"

int main(int argc, char* argv[]) {
    QApplication app(argc, argv);
    EditorWindow win;
    win.show();
    return app.exec();
}
