#include "../include/GameWindow.h"
#include "../include/DSA.h"
#include "ui_GameWindow.h"       // auto-generated from GameWindow.ui
#include <QVBoxLayout>
#include <QPushButton>
#include <QLabel>
#include <QKeyEvent>
#include <QHeaderView>
#include <QFile>
#include <QTextStream>
#include <QApplication>
#include <QLineEdit>
#include <cstring>
#include <QUrl>
#include <QTimer>

// ── GameWindow Constructor ─────────────────────────────────────
// Sets up the main window, the game engine, and the media players.
// The UI layout is loaded from GameWindow.ui (auto-generated by Qt's uic tool).
GameWindow::GameWindow(QWidget* parent) : QMainWindow(parent), scoreCount(0)
{
    currentPlayerName = "PlayerX";

    // Load the .ui layout — this creates all widgets, layouts, and object names
    // that were previously built manually in the old buildUI() function.
    ui = new Ui::GameWindowUI;
    ui->setupUi(this);

    // Initialize the screen navigation stack (DSA: Stack)
    screenStackInit(&screenHistory);

    // Create the game engine and connect its signals to our functions
    eng = new GameEngine(this);

    // QT SIGNAL SLOT SYSTEM
    // connecting Signals to our slots
    // connect(WHO_FIRES, WHAT_EVENT, WHO_HANDLES, WHICH_METHOD)
    connect(eng, &GameEngine::frameReady,   this, &GameWindow::onFrameReady);
    connect(eng, &GameEngine::stateChanged, this, &GameWindow::onStateChanged);

    // Setup background music based on Qt version
#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
    playlist = new QMediaPlaylist(this);
    playlist->addMedia(QUrl("qrc:/sounds/bgm.mp3"));
    playlist->setPlaybackMode(QMediaPlaylist::Loop);
    bgMusic = new QMediaPlayer(this);
    bgMusic->setPlaylist(playlist);
    bgMusic->setVolume(50);
    // Run playBGM() once after event loop starts
    QTimer::singleShot(0, this, &GameWindow::playBGM);
#else
    bgMusic = new QMediaPlayer(this);
    audioOutput = new QAudioOutput(this);
    bgMusic->setAudioOutput(audioOutput);
    bgMusic->setSource(QUrl("qrc:/sounds/bgm.mp3"));
    audioOutput->setVolume(0.5);
    bgMusic->setLoops(-1);
    // Run playBGM() once after event loop starts
    QTimer::singleShot(0, this, &GameWindow::playBGM);
#endif

    // ── Inject the GameRenderer into Page 0 ──────────────────
    // Page 0 is an empty placeholder in the .ui file because
    // GameRenderer is a custom widget that can't be placed in Qt Designer.
    // We create it here and add it to the pre-made layout.
    renderer = new GameRenderer(eng, ui->gamePage);
    ui->gameLayout->addWidget(renderer);

    // ── Finish table setup (properties that .ui can't fully express) ──
    ui->lbTable->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch);
    ui->lbTable->verticalHeader()->hide();

    // Wire up all button clicks and input signals
    setupConnections();

    // Load previous scores from file
    loadScores();
}

GameWindow::~GameWindow()
{
    delete ui;
}

// ── setupConnections ──────────────────────────────────────────
// Connects all UI button clicks to their handler functions.
// This replaces the connect() calls that were scattered inside
// the old buildUI() function.
void GameWindow::setupConnections()
{
    // Main Menu buttons
    connect(ui->btnPlay,        &QPushButton::clicked, this, &GameWindow::startGame);
    connect(ui->btnLeaderboard, &QPushButton::clicked, this, &GameWindow::showLeaderboard);
    connect(ui->btnQuit_menu,   &QPushButton::clicked, qApp, &QApplication::quit);

    // Leaderboard Back button
    connect(ui->btnBack, &QPushButton::clicked, this, &GameWindow::showMenu);

    // Name Entry buttons
    connect(ui->btnSubmit,   &QPushButton::clicked, this, &GameWindow::submitName);
    connect(ui->nameInput,   &QLineEdit::returnPressed, this, &GameWindow::submitName);

    // Menu Back button
    connect(ui->btnBack_menu, &QPushButton::clicked, this, [this]() {
        navigateTo(3);
    });
}

// ── playBGM ───────────────────────────────────────────────────
// Starts the background music. Called once after the Qt event loop starts.
void GameWindow::playBGM()
{
    if (bgMusic) {
        bgMusic->play();
    }
}

// ── Screen Navigation (DSA: Stack) ────────────────────────────
// navigateTo: pushes the current screen onto the stack, then switches
// navigateBack: pops the stack and goes to the previous screen
void GameWindow::navigateTo(int screenIndex)
{
    int currentScreen = ui->stack->currentIndex();
    screenStackPush(&screenHistory, currentScreen);
    ui->stack->setCurrentIndex(screenIndex);
}

void GameWindow::navigateBack()
{
    int previousScreen = screenStackPop(&screenHistory);
    if (previousScreen >= 0) {
        ui->stack->setCurrentIndex(previousScreen);
    } else {
        // Stack is empty — go to Name Entry as default
        ui->stack->setCurrentIndex(3);
    }
}

// ── Screen Transitions ────────────────────────────────────────
void GameWindow::startGame()
{
    eng->levels.current = eng->levels.head;
    navigateTo(0);              // push current screen, switch to game
    renderer->setFocus();       // ensure key presses go to the game
    eng->start();
}

void GameWindow::showMenu()
{
    navigateTo(1);              // push current screen, switch to menu
}

void GameWindow::showLeaderboard()
{
    refreshLeaderboard();
    navigateTo(2);              // push current screen, switch to leaderboard
}

void GameWindow::submitName()
{
    QString name = ui->nameInput->text().trimmed();
    if (!name.isEmpty()) {
        currentPlayerName = name;
    }
    navigateTo(1);              // push current screen, switch to menu
}

// ── Game Engine Callbacks ─────────────────────────────────────
void GameWindow::onFrameReady()
{
    renderer->update(); // tell the renderer to redraw the screen
}

void GameWindow::onStateChanged(int s)
{
    renderer->update();

    // Check if this is the final level win (no next level exists)
    bool hasNextLevel = false;
    if (eng->levels.current != nullptr) {
        if (eng->levels.current->next != nullptr) {
            hasNextLevel = true;
        }
    }
    bool isFinalWin = (s == STATE_WIN) && !hasNextLevel;

    // Save score on game over OR final level win
    if (isFinalWin || s == STATE_GAMEOVER) {
        int levelNum = 1;
        if (eng->levels.current != nullptr) {
            levelNum = eng->levels.current->data.num;
        }
        saveScore(currentPlayerName, eng->score, levelNum);
    }
}

// ── Leaderboard Logic ─────────────────────────────────────────
void GameWindow::saveScore(const QString& name, int score, int level)
{
    // Add new score if we have room
    if (scoreCount < MAX_SCORES) {
        ScoreEntry& e = scores[scoreCount];
        strncpy(e.name, name.toUtf8().constData(), 31);
        e.name[31] = 0;
        e.score = score;
        e.level = level;
        scoreCount++;
    } else {
        // Replace the lowest score if the new one is higher
        if (score > scores[MAX_SCORES - 1].score) {
            ScoreEntry& e = scores[MAX_SCORES - 1];
            strncpy(e.name, name.toUtf8().constData(), 31);
            e.name[31] = 0;
            e.score = score;
            e.level = level;
        }
    }

    // Sort all scores highest to lowest using QuickSort
    quickSort(scores, 0, scoreCount - 1);

    // Save them to a text file
    QFile f("scores.txt");
    if (f.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream out(&f);
        for (int i = 0; i < scoreCount; i++) {
            out << scores[i].name << "," << scores[i].score << ","
                << scores[i].level << "\n";
        }
    }
}

void GameWindow::loadScores()
{
    scoreCount = 0;
    QFile f("scores.txt");
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return;
    }

    QTextStream in(&f);
    while (!in.atEnd() && scoreCount < MAX_SCORES) {
        QStringList parts = in.readLine().split(",");
        if (parts.size() < 3) {
            continue;
        }
        strncpy(scores[scoreCount].name, parts[0].toUtf8().constData(), 31);
        scores[scoreCount].score = parts[1].toInt();
        scores[scoreCount].level = parts[2].toInt();
        scoreCount++;
    }
    if (scoreCount > 0) {
        quickSort(scores, 0, scoreCount - 1);
    }
}

void GameWindow::refreshLeaderboard()
{
    ui->lbTable->setRowCount(scoreCount);
    for (int i = 0; i < scoreCount; i++) {
        // Find the rank using Binary Search
        int rank = binarySearch(scores, scoreCount, scores[i].score) + 1;

        ui->lbTable->setItem(i, 0, new QTableWidgetItem(QString::number(rank)));
        ui->lbTable->setItem(i, 1, new QTableWidgetItem(scores[i].name));
        ui->lbTable->setItem(i, 2, new QTableWidgetItem(QString::number(scores[i].score)));
        ui->lbTable->setItem(i, 3, new QTableWidgetItem(QString::number(scores[i].level)));

        // Center text in all cells
        for (int c = 0; c < 4; c++) {
            QTableWidgetItem* item = ui->lbTable->item(i, c);
            if (item != nullptr) {
                item->setTextAlignment(Qt::AlignCenter);
            }
        }
    }
}

// ── Keyboard Controls ─────────────────────────────────────────
void GameWindow::keyPressEvent(QKeyEvent* e)
{
    // Only handle game-related key shortcuts when the game page is active
    if (ui->stack->currentIndex() != 0) {
        QMainWindow::keyPressEvent(e);
        return;
    }

    int s = eng->state;

    // Enter/Space can start or resume the game
    if (e->key() == Qt::Key_Return || e->key() == Qt::Key_Space) {
        if (s == STATE_MENU) {
            startGame();
            return;
        }
        if (s == STATE_PAUSED) {
            eng->resume();
            return;
        }
        if (s == STATE_WIN) {
            bool hasNextLevel = false;
            if (eng->levels.current != nullptr) {
                if (eng->levels.current->next != nullptr) {
                    hasNextLevel = true;
                }
            }
            if (hasNextLevel) {
                // More levels remain — advance
                eng->nextLevel();
            } else {
                // Final level complete — go straight to the leaderboard
                eng->state = STATE_MENU;
                showLeaderboard();
            }
            return;
        }
    }

    // R restarts the game
    if (e->key() == Qt::Key_R) {
        if (s == STATE_DEAD || s == STATE_GAMEOVER || s == STATE_WIN) {
            eng->start();
            return;
        }
    }

    // Esc pauses the game
    if (e->key() == Qt::Key_Escape) {
        if (s == STATE_PAUSED) {
            eng->resume();
            return;
        }
    }

    // Cheat code: Ctrl+L = extra life
    if (e->key() == Qt::Key_L) {
        bool ctrlHeld = (e->modifiers() & Qt::ControlModifier);
        if (ctrlHeld && s == STATE_PLAYING) {
            eng->lives++;
            emit eng->scoreChanged(eng->score);
            return;
        }
    }

    // Pass other keys to the game engine
    eng->keyPress(e->key());
}

void GameWindow::keyReleaseEvent(QKeyEvent* e)
{
    eng->keyRelease(e->key());
}

void GameWindow::closeEvent(QCloseEvent* e)
{
    e->accept(); // Let the window close normally
}

